#pragma once
#include "AxisParam.h"

enum AXIS_ID
{
#if(AMT_TYPE == 1)
	// MP2141 #1
	AXIS_SVO_LOAD_CONV,
	AXIS_SVO_LD_UPPERSHUTTLE_Y, 
	AXIS_SVO_LD_LOWERSHUTTLE_Y,
	AXIS_SVO_PREALIGN_TR_Y,
	AXIS_SVO_PREALIGN_TR_Z,
	AXIS_SVO_PA_STAGE_X,
	AXIS_SVO_LD_TR_X,
	AXIS_SVO_LD_TR_Z,
	AXIS_SVO_ALIGN_CAM_Y,
	AXIS_SVO_INS_X,
	AXIS_SVO_INS_CH1_Z,
	AXIS_SVO_INS_CH2_Z,

	// MP2141 #2
	AXIS_SVO_GOOD_TRAY_TR_Y,
	AXIS_SVO_GOOD_TRAY_TR_Z,
	AXIS_SVO_GOOD_TRAY_OUT_LIFT_Z,
	AXIS_SVO_GOOD_TRAY_IN_LIFT_Z,
	AXIS_SVO_ULD_TR_X,
	AXIS_SVO_ULD_TR_Z,
	AXIS_SVO_NG_TRAY_IN_LIFT_Z,
	AXIS_SVO_NG_TRAY_OUT_LIFT_Z,
	AXIS_SVO_NG_TRAY_TR_X,
	AXIS_SVO_NG_TRAY_TR_Z,

	// NMC(Not Servo Axis)#1
	AXIS_STP_PA_CH1_X,
	AXIS_STP_PA_CH2_X,
	AXIS_STP_PA_CH1_Y,
	AXIS_STP_PA_CH2_Y,
	AXIS_STP_PA_CH1_T,
	AXIS_STP_PA_CH2_T,
	AXIS_SVO_TURN_TABLE_T,

	// NMC(Not Servo Axis)#2
	AXIS_STP_ALIGN_CAM_X,
	AXIS_STP_RESERVED,
	AXIS_STP_INS_CH1_T,
	AXIS_STP_INS_CH2_T,
	AXIS_STP_INS_CH1_F,
	AXIS_STP_INS_CH2_F,

	AXIS_ID_MAX
#else
	AXIS_SVO_LOAD_CONV,
	AXIS_SVO_LD_UPPERSHUTTLE_Y, 
	AXIS_SVO_LD_LOWERSHUTTLE_Y,
	AXIS_SVO_PREALIGN_TR_Y,
	AXIS_SVO_PREALIGN_TR_Z,
	AXIS_SVO_PA_STAGE_X,
	AXIS_SVO_LD_TR_X,
	AXIS_SVO_LD_TR_Z,
	AXIS_SVO_ALIGN_CAM_Y,
	AXIS_SVO_INS_X,
	AXIS_SVO_INS_CH1_Z,
	AXIS_SVO_INS_CH2_Z,

	// MP2141 #2
	AXIS_SVO_ULD_TR_X,
	AXIS_SVO_ULD_TR_Z,
	AXIS_SVO_GOOD_TRAY_OUT_LIFT_Z,
	AXIS_SVO_GOOD_TRAY_IN_LIFT_Z,
	AXIS_SVO_GOOD_TRAY_TR_Y,
	AXIS_SVO_GOOD_TRAY_TR_Z,
	AXIS_SVO_NG_TRAY_IN_LIFT_Z,
	AXIS_SVO_NG_TRAY_OUT_LIFT_Z,
	AXIS_SVO_NG_TRAY_TR_X,
	AXIS_SVO_NG_TRAY_TR_Z,

	// NMC(Not Servo Axis)#1
	AXIS_STP_PA_CH1_X,
	AXIS_STP_PA_CH2_X,
	AXIS_STP_PA_CH1_Y,
	AXIS_STP_PA_CH2_Y,
	AXIS_STP_PA_CH1_T,
	AXIS_STP_PA_CH2_T,
	AXIS_SVO_TURN_TABLE_T,

	// NMC(Not Servo Axis)#2
	AXIS_STP_ALIGN_CAM_X,
	AXIS_STP_RESERVED,
	AXIS_STP_INS_CH1_T,
	AXIS_STP_INS_CH2_T,
	AXIS_STP_INS_CH1_F,
	AXIS_STP_INS_CH2_F,

	AXIS_ID_MAX
#endif
};

class CAxisParamBank
{
public:
	CAxisParamBank(void);
	~CAxisParamBank(void);

	CAxisParam m_Axis[AXIS_ID_MAX];

	void InitializeAxisType();

	void ReadAxisParam();
	void SaveAxisParam();

	BOOL MotorIsUsed(AXIS_ID id);
	BOOL GetParamNode(AXIS_ID id, CAxisParam& node);

};

