#pragma once


//2018-03-03,SKCHO 
////////////////////MELSEC_ADDRESS///////////////////////
#define MELSEC_SW_VERSION                           0X53C
#define MELSEC_EQID                                 0X550
#define MELSEC_PPID                                 0X564
#define MELSEC_CRST                                 0X578
#define MELSEC_AVAILABILITY							0X57C
#define MELSEC_INTERLOCK							0X57D
#define MELSEC_MOVE									0X57E
#define MELSEC_RUN									0X57F
#define MELSEC_FRONT								0X580
#define MELSEC_MCR1_STATUS							0X585	//LOWER
#define MELSEC_MCR2_STATUS							0X586	//UPPER

//LD ROBOT TEACHING DATA -> X,Y,Z,T 
#define MELSEC_LDROBOT_X							0X587
#define MELSEC_LDROBOT_Y							0X58C
#define MELSEC_LDROBOT_Z							0X591
#define MELSEC_LDROBOT_T							0X596
#define MELSEC_ULDROBOT_CH1_X						0X59B
#define MELSEC_ULDROBOT_CH1_Y						0X5A0
#define MELSEC_ULDROBOT_CH1_Z						0X5A5
#define MELSEC_ULDROBOT_CH1_T						0X5AA
#define MELSEC_ULDROBOT_CH2_X						0X5AF
#define MELSEC_ULDROBOT_CH2_Y						0X5B4
#define MELSEC_ULDROBOT_CH2_Z						0X5B9
#define MELSEC_ULDROBOT_CH2_T						0X5BE

//EDGE ALIGN
#define MELSEC_EDGE_ALIGN_RESULT					0X5C3
#define MELSEC_EDGE_ALIGN_X							0X5C4
#define MELSEC_EDGE_ALIGN_Y							0X5CE
#define MELSEC_EDGE_ALIGN_T							0X5D8

//PRE ALIGN
/////////////CH1/////////////////
#define MELSEC_PRE_ALIGN_CH1_RESULT					0X5E2
#define MELSEC_PRE_ALIGN_CH1_X						0X5E3
#define MELSEC_PRE_ALIGN_CH1_Y						0X5E8
#define MELSEC_PRE_ALIGN_CH1_T						0X5ED
/////////////CH2/////////////////
#define MELSEC_PRE_ALIGN_CH2_RESULT					0X5F2
#define MELSEC_PRE_ALIGN_CH2_X						0X5F3
#define MELSEC_PRE_ALIGN_CH2_Y						0X5F8
#define MELSEC_PRE_ALIGN_CH2_T						0X5FD
//MCR CELL ID
#define MELSEC_MCR_CH1_CELL_ID						0X602
#define MELSEC_MCR_CH2_CELL_ID						0X616

//DCR TRAY ID
#define MELSEC_DCR_ID								0X62A

//Tact Time(LD, A,B,C,D ZONE , ULD)
#define MELSEC_TACT_TIME_LD							0X63E
#define MELSEC_TACT_TIME_AZONE						0X643
#define MELSEC_TACT_TIME_BZONE						0X648
#define MELSEC_TACT_TIME_CZONE						0X64D
#define MELSEC_TACT_TIME_DZONE						0X652
#define MELSEC_TACT_TIME_ULD						0X657

//컨택률
#define MELSEC_CONTACT_RATE							0X65C
#define MELSEC_CONTACT_RATE_DAY						0X661
#define MELSEC_CONTACT_RATE_WEEK					0X666
#define MELSEC_CONTACT_RATE_MONTH					0X66B

//생산량
#define MELSEC_PRODUCTION_QUANTITY					0X670
#define MELSEC_PRODUCTION_QUANTITY_DAY				0X675
#define MELSEC_PRODUCTION_QUANTITY_WEEK				0X67A
#define MELSEC_PRODUCTION_QUANTITY_MONTH			0X67F

//2018-03-09,MGYUN/NAM define 작업

//Port Status ,(Port 관리 설비 전용)
/*
	1 : GOOD IN BUF
	2 : GOOD IN
	3 : GOOD OUT
	4 : GOOD OUT BUF
	5 : NG OUT BUF
	6 : NG IN 
*/
			// 1 : GOOD IN BUF
#define MELSEC_PORTNO_1								0X684
#define MELSEC_PORTAVAILSTATE_1						0X685
#define MELSEC_PORTACCESSMODE_1						0X686
#define	MELSEC_PORTTRANSFERSTATE_1					0X687
#define MELSEC_PORTPROCESSINGSTATE_1				0X688

			// 2 :GOOD IN
#define MELSEC_PORTNO_2								0X689
#define MELSEC_PORTAVAILSTATE_2						0X68A
#define MELSEC_PORTACCESSMODE_2						0X68B
#define	MELSEC_PORTTRANSFERSTATE_2					0X68C
#define MELSEC_PORTPROCESSINGSTATE_2				0X68D

			// 3 : GOOD OUT 
#define MELSEC_PORTNO_3								0X68E
#define MELSEC_PORTAVAILSTATE_3						0X68F
#define MELSEC_PORTACCESSMODE_3						0X690
#define	MELSEC_PORTTRANSFERSTATE_3					0X691
#define MELSEC_PORTPROCESSINGSTATE_3				0X692

			// 4 : GOOD OUT BUF
#define MELSEC_PORTNO_4								0X693
#define MELSEC_PORTAVAILSTATE_4						0X694
#define MELSEC_PORTACCESSMODE_4						0X695
#define	MELSEC_PORTTRANSFERSTATE_4					0X696
#define MELSEC_PORTPROCESSINGSTATE_4				0X697

			// 5 : NG OUT BUF
#define MELSEC_PORTNO_5								0X698
#define MELSEC_PORTAVAILSTATE_5						0X699
#define MELSEC_PORTACCESSMODE_5						0X69A
#define	MELSEC_PORTTRANSFERSTATE_5					0X69B
#define MELSEC_PORTPROCESSINGSTATE_5				0X69C

			// 6 : NG IN
#define MELSEC_PORTNO_6								0X69D
#define MELSEC_PORTAVAILSTATE_6						0X69E
#define MELSEC_PORTACCESSMODE_6						0X69F
#define	MELSEC_PORTTRANSFERSTATE_6					0X6A0
#define MELSEC_PORTPROCESSINGSTATE_6				0X6A1

//LOADER
#define   MELSEC_LD_UPPERSHUTTLE_Y					0X6A2
#define	  MELSEC_LD_LOWERSHUTTLE_Y					0x6A7
#define	  MELSEC_PREALIGN_TR_Y						0x6AC
#define   MELSEC_PREALIGN_TR_Z						0x6B1
#define   MELSEC_PA_STAGE_X							0x6B6
#define   MELSEC_LD_TR_X							0x6BB
#define   MELSEC_LD_TR_Z							0x6C0

//INS_AZONE_CH1
#define   MELSEC_INS_AZONE_CH1_CELL_ID				0x6C5
#define	  MELSEC_INS_AZONE_CH1_STEP_ID				0x6D9
#define   MELSEC_A_ZONE_CH1_VAC						0x6DA

//INS_AZONE_CH2
#define   MELSEC_INS_AZONE_CH2_CELL_ID				0x6DF
#define   MELSEC_INS_AZONE_CH2_STEP_ID				0x6F3
#define   MELSEC_A_ZONE_CH2_VAC						0x6F4

//INS_BZONE_CH1
#define   MELSEC_INS_BZONE_CH1_CELL_ID				0x6F9
#define	  MELSEC_INS_BZONE_CH1_STEP_ID				0x70D
#define   MELSEC_B_ZONE_CH1_VAC						0x70E

//INS_BZONE_CH2
#define   MELSEC_INS_BZONE_CH2_CELL_ID				0x713
#define   MELSEC_INS_BZONE_CH2_STEP_ID				0x727
#define   MELSEC_B_ZONE_CH2_VAC						0x728

//INS_CZONE_CH1
#define   MELSEC_INS_CZONE_CH1_CELL_ID				0x72D
#define	  MELSEC_INS_CZONE_CH1_STEP_ID				0x741
#define   MELSEC_C_ZONE_CH1_VAC						0x742

//INS_CZONE_CH2
#define   MELSEC_INS_CZONE_CH2_CELL_ID				0x747
#define   MELSEC_INS_CZONE_CH2_STEP_ID				0x75B
#define   MELSEC_C_ZONE_CH2_VAC						0x75C

//INS_DZONE_CH1
#define   MELSEC_INS_DZONE_CH1_CELL_ID				0x761
#define	  MELSEC_INS_DZONE_CH1_STEP_ID				0x775
#define   MELSEC_D_ZONE_CH1_VAC						0x776

//INS_DZONE_CH2
#define   MELSEC_INS_DZONE_CH2_CELL_ID				0x77B
#define   MELSEC_INS_DZONE_CH2_STEP_ID				0x78F
#define   MELSEC_D_ZONE_CH2_VAC						0x790

//ULD_TR_CH1
#define   MELSEC_ULD_TR_CH1_CELL_ID					0x795
#define	  MELSEC_ULD_TR_CH1_STEP_ID					0x7A9
#define   MELSEC_ULD_TR_CH1_VAC						0x7AA

//ULD_TR_CH2
#define   MELSEC_ULD_TR_CH2_CELL_ID					0x7AF
#define	  MELSEC_ULD_TR_CH2_STEP_ID					0x7C3
#define   MELSEC_ULD_TR_CH2_VAC						0x7C4

//ULD_STAGE_CH1
#define   MELSEC_ULD_STAGE_CH1_CELL_ID				0x7C9
#define	  MELSEC_ULD_STAGE_CH1_STEP_ID				0x7DD
#define   MELSEC_ULD_STAGE_CH1_VAC					0x7DE
//ULD_STAGE_CH2
#define   MELSEC_ULD_STAGE_CH2_CELL_ID				0x7E3
#define	  MELSEC_ULD_STAGE_CH2_STEP_ID				0x7F7
#define   MELSEC_ULD_STAGE_CH2_VAC					0x7F8

//GOOD TRAY
#define   MELSEC_GOOD_TRAY_IN_LIFT_Z				0x7FD
#define   MELSEC_GOOD_TRAY_OUT_LIFT_Z				0x802
#define   MELSEC_GOOD_TRAY_TR_Y						0x807
#define   MELSEC_GOOD_TRAY_TR_Z						0x80C

//NG TRAY
#define   MELSEC_NG_TRAY_IN_LIFT_Z					0x811
#define   MELSEC_NG_TRAY_OUT_LIFT_Z					0x816
#define   MELSEC_NG_TRAY_TR_Y						0x81B
#define   MELSEC_NG_TRAY_TR_Z						0x820

				//UTIL 
#define MELSEC_PC_RACK_TEMP							0X825
#define MELSEC_EFU_ALARM							0X82A
#define MELSEC_MAIN_AIR1							0X82B
#define MELSEC_MAIN_AIR2							0X830
#define MELSEC_MAIN_VAC1							0X835
#define MELSEC_MAIN_VAC2							0X83A
#define MELSEC_GMS_1								0X83F
#define MELSEC_GMS_2								0X844
#define MELSEC_GMS_3								0X849
#define MELSEC_GMS_4								0X84E
#define MELSEC_GMS_5								0X853
#define MELSEC_PGMS_1								0X858
#define MELSEC_PGMS_2								0X85D

			//SEM
#define MELSEC_THREE_PHASE_POWER1					0X862
#define MELSEC_INSTANTANEOUS_POWER1					0X867
#define MELSEC_R_PHASE_VOLTAGE1						0X86C
#define MELSEC_T_PHASE_VOLTAGE1						0X871
#define MELSEC_R_PHASE_CURRENT1						0X876
#define MELSEC_T_PHASE_CURRENT1						0X87B
#define MELSEC_THREE_PHASE_POWER2					0X880
#define MELSEC_INSTANTANEOUS_POWER2					0X885
#define MELSEC_R_PHASE_VOLTAGE2						0X88A
#define MELSEC_R_PHASE_CURRENT2						0X88F

			//STEP ID 
#define MELSEC_LD_CONV_STEP_ID						0X894
#define MELSEC_LD_ROBOT_STEP_ID						0X895
#define MELSEC_LD_UPPER_SHUTTLE_CH1_STEP_ID			0X896
#define MELSEC_LD_UPPER_SHUTTLE_CH2_STEP_ID			0X897
#define MELSEC_LD_LOWER_SHUTTLE_CH1_STEP_ID			0X898
#define MELSEC_LD_LOWER_SHUTTLE_CH2_STEP_ID			0X899
#define MELSEC_PRE_ALIGN_TR_CH1_STEP_ID				0X89A
#define MELSEC_PRE_ALIGN_TR_CH2_STEP_ID				0X89B
#define MELSEC_PRE_ALIGN_STAGE_CH1_STEP_ID			0X89C
#define MELSEC_PRE_ALIGN_STAGE_CH2_STEP_ID			0X89D
#define MELSEC_LD_TR_CH1_STEP_ID					0X89E
#define MELSEC_LD_TR_CH2_STEP_ID					0X89F
#define MELSEC_ULD_ROBOT_STEP_ID					0X8A0


//상류설비로 부터 지연 시간/ AGV IN, OUT 지연 시간
#define MELSEC_IN_DELAY								0X8A1
#define MELSEC_AGV_IN_DELAY							0X8A6
#define MELSEC_AGV_OUT_DELAY						0X8AB

//2018-03-13,MGYUN, CELL 관련 항목 정의
#define MELSEC_CELL_CH1_INNER_ID					0X8B0
#define MELSEC_CELL_CH1_MODEL						0X8C4
#define MELSEC_CELL_CH1_JIG_NAME					0X8D8
#define MELSEC_CELL_CH1_CH_NAME						0X8D9
#define MELSEC_CELL_CH1_ALIGN_RESULT				0X8DA
#define MELSEC_CELL_CH1_CONTACT_RESULT				0X8DB		
#define MELSEC_CELL_CH1_VERSION						0X8DC
#define MELSEC_CELL_CH1_TMD_NAME					0X8F0
#define MELSEC_CELL_CH1_INSP_TACT_TIME				0X904
#define MELSEC_CELL_CH1_INSP_RESULT					0X909	
#define MELSEC_CELL_CH1_INSP_CODE					0X90A

#define MELSEC_CELL_CH2_INNER_ID					0X90F
#define MELSEC_CELL_CH2_MODEL						0X923
#define MELSEC_CELL_CH2_JIG_NAME					0X937
#define MELSEC_CELL_CH2_CH_NAME						0X938
#define MELSEC_CELL_CH2_ALIGN_RESULT				0X939
#define MELSEC_CELL_CH2_CONTACT_RESULT				0X93A		
#define MELSEC_CELL_CH2_VERSION						0X93B
#define MELSEC_CELL_CH2_TMD_NAME					0X94F
#define MELSEC_CELL_CH2_INSP_TACT_TIME				0X963
#define MELSEC_CELL_CH2_INSP_RESULT					0X968
#define MELSEC_CELL_CH2_INSP_CODE					0X969

#define MELSEC_TURNTABLE_POS						0X96E
//2018-03-15,MGYUN, 지그별 스킵 상태
#define MELSEC_AJIG_SKIP_STATUS						0X96F
#define MELSEC_BJIG_SKIP_STATUS						0X970
#define MELSEC_CJIG_SKIP_STATUS						0X971
#define MELSEC_DJIG_SKIP_STATUS						0X972
//INTER LOCK STATUS
#define MELSEC_INTERLOCK_NAME						0X973
#define MELSEC_INTERLOCK_STATUS						0X987

//2018-03-13,MGYUN,추가 알람
#define MELSEC_ALARM_CODE						0X10DB
#define MELSEC_ALARM_CAUSE_CODE					0X113F

//2018-03-14,MGYUN, 요청으로 ALARM 상태 추가 (0 : 알람 미발생, 1 : 알람 발생)
#define MELSEC_FDC_ALARM_STATUS					0X11A3
#define MELSEC_FDC_ALARM_CASUE					0X11A4


/* // OPTION
#define MELSEC_OPTION_AGV_WAIT_TIME
#define MELSEC_OPTION_UPPER_IF_WAIT_TIME
#define MELSEC_OPTION_USE_DRY_RUN
#define MELSEC_OPTION_USE_LOT_END
#define MELSEC_OPTION_USE_UPPER_MCR_READ
#define MELSEC_OPTION_USE_LOWER_MCR_READ
#define MELSEC_OPTION_USE_EDGE_ALIGN
#define MELSEC_OPTION_USE_VI_ALIGN
#define MELSEC_OPTION_USE_PREALIGN
#define MELSEC_OPTION_USE_LOGIN_REQUEST
#define MELSEC_OPTION_USE_MANUAL_RECEIVE
#define MELSEC_OPTION_USE_RCMD
#define MELSEC_OPTION_USE_VIINSP
#define MELSEC_OPTION_USE_TRAYALIGN
#define MELSEC_OPTION_USE_CONTACT
#define MELSEC_OPTION_USE_JUDGEOK
#define MELSEC_OPTION_USE_CELLINFO_SKIP
#define MELSEC_OPTION_USE_JOB_END
#define MELSEC_OPTION_JOB_END_TIME
#define MELSEC_OPTION_GRAB_END_WAIT_TIME
#define MELSEC_OPTION_CLASS_END_WAIT_TIME
#define MELSEC_OPTION_MAX_GOOD_TRAY_COUNT
#define MELSEC_OPTION_MAX_NG_TRAY_COUNT
#define MELSEC_OPTION_VISION_CONTINUES_NGCNT
#define MELSEC_OPTION_RUNDOWN_WAIT_TIME
#define MELSEC_OPTION_MCR_DELAY_TIME
#define MELSEC_OPTION_TRAY_ID_COUNT
#define MELSEC_OPTION_AGV_DELAY_TIME
#define MELSEC_OPTION_LDTRB_LOWER_OFFTIME
#define MELSEC_OPTION_CELLINFO_WAIT_TIME
#define MELSEC_OPTION_CARRIER_INFO_WAIT_TIME
#define MELSEC_OPTION_T5_RESTART_TIME
#define MELSEC_OPTION_GOOD_TR_RETRY_LENGTH
#define MELSEC_OPTION_NGTRRETRY_LENGTH
#define MELSEC_OPTION_USE_A_SKIP
#define MELSEC_OPTION_A_SKIP_DESCRIPTION
#define MELSEC_OPTION_USE_B_SKIP
#define MELSEC_OPTION_B_SKIP_DESCRIPTION
#define MELSEC_OPTION_USE_C_SKIP
#define MELSEC_OPTION_C_SKIP_DESCRIPTION
#define MELSEC_OPTION_USE_D_SKIP
#define MELSEC_OPTION_D_SKIP_DESCRIPTION

#define MELSEC_OPTION_USE_A_CH1_SKIP 
#define MELSEC_OPTION_USE_B_CH1_SKIP
#define MELSEC_OPTION_USE_C_CH1_SKIP 
#define MELSEC_OPTION_USE_D_CH1_SKIP
#define MELSEC_OPTION_USE_A_CH2_SKIP 
#define MELSEC_OPTION_USE_B_CH2_SKIP
#define MELSEC_OPTION_USE_C_CH2_SKIP 
#define MELSEC_OPTION_USE_D_CH2_SKIP
#define MELSEC_OPTION_USE_CONTACT_RETRY
#define MELSEC_OPTION_USE_CARRIER_REPORT_SKIP
#define MELSEC_OPTION_USE_REPEAT_INSP
#define MELSEC_OPTION_LOAD_PITCHIN
#define MELSEC_OPTION_STR_REJECT_CODE
#define MELSEC_OPTION_GRAB_MCR_USE
#define MELSEC_OPTION_DIVISION
#define MELSEC_OPTION_SKIP_LD_CONV_SEN3
#define MELSEC_OPTION_USE_ULD_TR_MODE
#define MELSEC_OPTION_USE_LDROBOT_RETRY
#define MELSEC_OPTION_USE_TRAY_VI
#define MELSEC_OPTION_USE_PATR_RETRY
#define MELSEC_OPTION_USE_JIG_BLOW
#define MELSEC_OPTION_PA_ORG_TIME
#define MELSEC_OPTION_USE_FPCB_SEN
#define MELSEC_OPTION_NGINLIFT_SEN1
#define MELSEC_OPTION_NGINLIFT_SEN2
#define MELSEC_OPTION_NGOUTLIFT_SEN1
#define MELSEC_OPTION_NGOUTLIFT_SEN2
//[FDC RANGE]
#define MELSEC_OPTION_UPS_VOLT_MAX
#define MELSEC_OPTION_UPS_VOLT_MIN
#define MELSEC_OPTION_UPS_CURRENT_MAX
#define MELSEC_OPTION_UPS_CURRENT_MIN
#define MELSEC_OPTION_GPS_VOLT_MAX
#define MELSEC_OPTION_GPS_VOLT_MIN
#define MELSEC_OPTION_GPS_CURRENT_MAX
#define MELSEC_OPTION_GPS_CURRENT_MIN
#define MELSEC_OPTION_GPS_POWER_MAX
#define MELSEC_OPTION_GPS_POWER_MIN
#define MELSEC_OPTION_GMS_MAX
#define MELSEC_OPTION_GMS_MIN
#define MELSEC_OPTION_AIR_MAX
#define MELSEC_OPTION_AIR_MIN
#define MELSEC_OPTION_VAC_MAX
#define MELSEC_OPTION_VAC_MIN

*/


////////////////////MELSEC_ADDRESS_LENGTH/////////////////
#define MELSEC_SW_VERSION_LENGTH                    20
#define MELSEC_EQID_LENGTH                          20
#define MELSEC_PPID_LENGTH                          20
#define MELSEC_CRST_LENGTH                          1
#define MELSEC_AVAILABILITY_LENGTH					1
#define MELSEC_INTERLOCK_LENGTH						1
#define MELSEC_MOVE_LENGTH							1
#define MELSEC_RUN_LENGTH							1
#define MELSEC_FRONT_LENGTH							1

//2018-03-08,MGYUN,추가
#define MELSEC_MCR1_LENGTH							1
#define MELSEC_MCR2_LENGTH							1
#define MELSEC_LDROBOT_X_LENGTH						5
#define MELSEC_LDROBOT_Y_LENGTH						5
#define MELSEC_LDROBOT_Z_LENGTH						5
#define MELSEC_LDROBOT_T_LENGTH						5

//ULD ROBOT TEACHING DATA / CH1,CH2

#define MELSEC_ULDROBOT_CH1_X_LENGTH				5
#define MELSEC_ULDROBOT_CH1_Y_LENGTH				5
#define MELSEC_ULDROBOT_CH1_Z_LENGTH				5
#define MELSEC_ULDROBOT_CH1_T_LENGTH				5
#define MELSEC_ULDROBOT_CH2_X_LENGTH				5
#define MELSEC_ULDROBOT_CH2_Y_LENGTH				5
#define MELSEC_ULDROBOT_CH2_Z_LENGTH				5
#define MELSEC_ULDROBOT_CH2_T_LENGTH				5
#define MELSEC_EDGE_ALIGN_RESULT_LENGTH				1
#define MELSEC_EDGE_ALIGN_X_LENGTH					10
#define MELSEC_EDGE_ALIGN_Y_LENGTH					10
#define MELSEC_EDGE_ALIGN_T_LENGTH					10

//PRE ALIGN
/////////////CH1/////////////////

#define MELSEC_PRE_ALIGN_CH1_LENGTH					5
#define MELSEC_PRE_ALIGN_CH1_X_LENGTH				5
#define MELSEC_PRE_ALIGN_CH1_Y_LENGTH				5
#define MELSEC_PRE_ALIGN_CH1_T_LENGTH				5
#define MELSEC_PRE_ALIGN_CH2_LENGTH					5
#define MELSEC_PRE_ALIGN_CH2_X_LENGTH				5					  
#define MELSEC_PRE_ALIGN_CH2_Y_LENGTH				5
#define MELSEC_PRE_ALIGN_CH2_T_LENGTH				5
#define MELSEC_MCR_CH1_CELL_ID_LENGTH				20
#define MELSEC_MCR_CH2_CELL_ID_LENGTH				20
#define MELSEC_DCR_ID_LENGTH						20

//TACT TIME
#define MELSEC_TACT_TIME_LD_LENGTH					5
#define MELSEC_TACT_TIME_AZONE_LENGTH				5
#define MELSEC_TACT_TIME_BZONE_LENGTH				5
#define MELSEC_TACT_TIME_CZONE_LENGTH				5
#define MELSEC_TACT_TIME_DZONE_LENGTH				5
#define MELSEC_TACT_TIME_ULD_LENGTH					5

//컨택률
#define MELSEC_CONTACT_RATE_LENGTH					5
#define MELSEC_CONTACT_RATE_DAY_LENGTH				5
#define MELSEC_CONTACT_RATE_WEEK_LENGTH				5
#define MELSEC_CONTACT_RATE_MONTH_LENGTH			5

//생산량
#define MELSEC_PRODUCTION_QUANTITY_LENGTH			5
#define MELSEC_PRODUCTION_QUANTITY_DAY_LENGTH		5
#define MELSEC_PRODUCTION_QUANTITY_WEEK_LENGTH		5
#define MELSEC_PRODUCTION_QUANTITY_MONTH_LENGTH		5

// 1 : GOOD IN BUF
#define MELSEC_PORTNO_1_LENGTH						1
#define MELSEC_PORTAVAILSTATE_1_LENGTH				1
#define MELSEC_PORTACCESSMODE_1_LENGTH				1
#define	MELSEC_PORTTRANSFERSTATE_1_LENGTH			1
#define MELSEC_PORTPROCESSINGSTATE_1_LENGTH			1

// 2 :GOOD IN
#define MELSEC_PORTNO_2_LENGTH						1
#define MELSEC_PORTAVAILSTATE_2_LENGTH				1
#define MELSEC_PORTACCESSMODE_2_LENGTH				1
#define	MELSEC_PORTTRANSFERSTATE_2_LENGTH			1
#define MELSEC_PORTPROCESSINGSTATE_2_LENGTH			1

// 3 : GOOD OUT
#define MELSEC_PORTNO_3_LENGTH						1
#define MELSEC_PORTAVAILSTATE_3_LENGTH				1
#define MELSEC_PORTACCESSMODE_3_LENGTH				1
#define	MELSEC_PORTTRANSFERSTATE_3_LENGTH			1
#define MELSEC_PORTPROCESSINGSTATE_3_LENGTH			1

// 4 : GOOD OUT BUF
#define MELSEC_PORTNO_4_LENGTH						1
#define MELSEC_PORTAVAILSTATE_4_LENGTH				1
#define MELSEC_PORTACCESSMODE_4_LENGTH				1
#define	MELSEC_PORTTRANSFERSTATE_4_LENGTH			1
#define MELSEC_PORTPROCESSINGSTATE_4_LENGTH			1

// 5 : NG OUT BUF
#define MELSEC_PORTNO_5_LENGTH						1
#define MELSEC_PORTAVAILSTATE_5_LENGTH				1
#define MELSEC_PORTACCESSMODE_5_LENGTH				1
#define	MELSEC_PORTTRANSFERSTATE_5_LENGTH			1
#define MELSEC_PORTPROCESSINGSTATE_5_LENGTH			1

// 6 : NG IN
#define MELSEC_PORTNO_6_LENGTH						1
#define MELSEC_PORTAVAILSTATE_6_LENGTH				1
#define MELSEC_PORTACCESSMODE_6_LENGTH				1
#define	MELSEC_PORTTRANSFERSTATE_6_LENGTH			1
#define MELSEC_PORTPROCESSINGSTATE_6_LENGTH			1

//LOADER
#define   MELSEC_LD_UPPERSHUTTLE_Y_LENGTH			5	
#define	  MELSEC_LD_LOWERSHUTTLE_Y_LENGTH			5			
#define   MELSEC_PREALIGN_TR_Y_LENGTH				5
#define	  MELSEC_PREALIGN_TR_Z_LENGTH               5
#define   MELSEC_PA_STAGE_X_LENGTH					5
#define   MELSEC_LD_TR_X_LENGTH						5
#define   MELSEC_LD_TR_Z_LENGTH						5

//INS_AZONE_CH1
#define   MELSEC_INS_AZONE_CH1_CELL_ID_LENGTH	    20
#define   MELSEC_INS_AZONE_CH1_STEP_ID_LENGTH		1
#define   MELSEC_A_ZONE_CH1_VAC_LENGTH				5

//INS_AZONE_CH2
#define   MELSEC_INS_AZONE_CH2_CELL_ID_LENGTH		20
#define   MELSEC_INS_AZONE_CH2_STEP_ID_LENGTH		1
#define   MELSEC_A_ZONE_CH2_VAC_LENGTH				5

//INS_BZONE_CH1
#define   MELSEC_INS_BZONE_CH1_CELL_ID_LENGTH	    20
#define   MELSEC_INS_BZONE_CH1_STEP_ID_LENGTH		1
#define   MELSEC_B_ZONE_CH1_VAC_LENGTH				5

//INS_BZONE_CH2
#define   MELSEC_INS_BZONE_CH2_CELL_ID_LENGTH		20
#define   MELSEC_INS_BZONE_CH2_STEP_ID_LENGTH		1
#define   MELSEC_B_ZONE_CH2_VAC_LENGTH				5

//INS_CZONE_CH1
#define   MELSEC_INS_CZONE_CH1_CELL_ID_LENGTH	    20
#define   MELSEC_INS_CZONE_CH1_STEP_ID_LENGTH		1
#define   MELSEC_C_ZONE_CH1_VAC_LENGTH				5

//INS_CZONE_CH2
#define   MELSEC_INS_CZONE_CH2_CELL_ID_LENGTH		20
#define   MELSEC_INS_CZONE_CH2_STEP_ID_LENGTH		1
#define   MELSEC_C_ZONE_CH2_VAC_LENGTH				5

//INS_DZONE_CH1
#define   MELSEC_INS_DZONE_CH1_CELL_ID_LENGTH	    20
#define   MELSEC_INS_DZONE_CH1_STEP_ID_LENGTH		1
#define   MELSEC_D_ZONE_CH1_VAC_LENGTH				5

//INS_DZONE_CH2
#define   MELSEC_INS_DZONE_CH2_CELL_ID_LENGTH		20
#define   MELSEC_INS_DZONE_CH2_STEP_ID_LENGTH		1
#define   MELSEC_D_ZONE_CH2_VAC_LENGTH				5

//ULD_TR_CH1
#define   MELSEC_ULD_TR_CH1_CELL_ID_LENGTH			20
#define   MELSEC_ULD_TR_CH1_STEP_ID_LENGTH			1
#define   MELSEC_ULD_TR_CH1_VAC_LENGTH				5

//ULD_TR_CH2
#define   MELSEC_ULD_TR_CH2_CELL_ID_LENGTH			20
#define   MELSEC_ULD_TR_CH2_STEP_ID_LENGTH			1
#define   MELSEC_ULD_TR_CH2_VAC_LENGTH				5

//ULD_STAGE_CH1
#define   MELSEC_ULD_STAGE_CH1_CELL_ID_LENGTH		20
#define   MELSEC_ULD_STAGE_CH1_STEP_ID_LENGTH		1
#define   MELSEC_ULD_STAGE_CH1_VAC_LENGTH			5

//ULD_STAGE_CH2
#define   MELSEC_ULD_STAGE_CH2_CELL_ID_LENGTH		20
#define   MELSEC_ULD_STAGE_CH2_STEP_ID_LENGTH		1
#define   MELSEC_ULD_STAGE_CH2_VAC_LENGTH			5

//GOOD TRAY
#define   MELSEC_GOOD_TRAY_IN_LIFT_Z_LENGTH	        5
#define   MELSEC_GOOD_TRAY_OUT_LIFT_Z_LENGTH		5
#define   MELSEC_GOOD_TRAY_TR_Y_LENGTH				5
#define   MELSEC_GOOD_TRAY_TR_Z_LENGTH				5

//NG TRAY
#define   MELSEC_NG_TRAY_IN_LIFT_Z_LENGTH	        5
#define   MELSEC_NG_TRAY_OUT_LIFT_Z_LENGTH			5
#define   MELSEC_NG_TRAY_TR_Y_LENGTH				5
#define   MELSEC_NG_TRAY_TR_Z_LENGTH				5

//UTIL 
#define MELSEC_PC_RACK_TEMP_LENGTH					5
#define MELSEC_EFU_ALARM_LENGTH						5
#define MELSEC_MAIN_AIR1_LENGTH						5
#define MELSEC_MAIN_AIR2_LENGTH						5
#define MELSEC_MAIN_VAC1_LENGTH						5
#define MELSEC_MAIN_VAC2_LENGTH						5
#define MELSEC_GMS_1_LENGTH							5
#define MELSEC_GMS_2_LENGTH							5
#define MELSEC_GMS_3_LENGTH							5
#define MELSEC_GMS_4_LENGTH							5
#define MELSEC_GMS_5_LENGTH							5
#define MELSEC_PGMS_1_LENGTH						5
#define MELSEC_PGMS_2_LENGTH						5

//SEM
#define MELSEC_THREE_PHASE_POWER1_LENGTH			5
#define MELSEC_INSTANTANEOUS_POWER1_LENGTH			5
#define MELSEC_R_PHASE_VOLTAGE1_LENGTH				5
#define MELSEC_T_PHASE_VOLTAGE1_LENGTH				5
#define MELSEC_R_PHASE_CURRENT1_LENGTH				5
#define MELSEC_T_PHASE_CURRENT1_LENGTH				5
#define MELSEC_THREE_PHASE_POWER2_LENGTH			5
#define MELSEC_INSTANTANEOUS_POWER2_LENGTH			5
#define MELSEC_R_PHASE_VOLTAGE2_LENGTH				5
#define MELSEC_R_PHASE_CURRENT2_LENGTH				5

//STEP ID
#define MELSEC_LD_CONV_STEP_ID_LENGTH				1
#define MELSEC_LD_ROBOT_STEP_ID_LENGTH				1
#define MELSEC_LD_UPPER_SHUTTLE_CH1_STEP_ID_LENGTH	1
#define MELSEC_LD_UPPER_SHUTTLE_CH2_STEP_ID_LENGTH	1
#define MELSEC_LD_LOWER_SHUTTLE_CH1_STEP_ID_LENGTH	1
#define MELSEC_LD_LOWER_SHUTTLE_CH2_STEP_ID_LENGTH	1
#define MELSEC_PRE_ALIGN_TR_CH1_STEP_ID_LENGTH		1
#define MELSEC_PRE_ALIGN_TR_CH2_STEP_ID_LENGTH		1
#define MELSEC_PRE_ALIGN_STAGE_CH1_STEP_ID_LENGTH	1
#define MELSEC_PRE_ALIGN_STAGE_CH2_STEP_ID_LENGTH	1
#define MELSEC_LD_TR_CH1_STEP_ID_LENGTH				1
#define MELSEC_LD_TR_CH2_STEP_ID_LENGTH				1
#define MELSEC_ULD_ROBOT_STEP_ID_LENGTH				1

//DLEAY TIME 길이
#define MELSEC_IN_DELAY_LENGTH						5
#define MELSEC_AGV_IN_DELAY_LENGTH					5
#define MELSEC_AGV_OUT_DELAY_LENGTH					5

//2018-03-13,MGYUN, CELL 관련 항목 정의
#define MELSEC_CELL_CH1_INNER_ID_LENGTH					20
#define MELSEC_CELL_CH1_MODEL_LENGTH					20
#define MELSEC_CELL_CH1_JIG_NAME_LENGTH					1
#define MELSEC_CELL_CH1_CH_NAME_LENGTH					1
#define MELSEC_CELL_CH1_ALIGN_RESULT_LENGTH				1
#define MELSEC_CELL_CH1_CONTACT_RESULT_LENGTH			1		
#define MELSEC_CELL_CH1_VERSION_LENGTH					20
#define MELSEC_CELL_CH1_TMD_NAME_LENGTH					20
#define MELSEC_CELL_CH1_INSP_TACT_TIME_LENGTH			5
#define MELSEC_CELL_CH1_INSP_RESULT_LENGTH				1	
#define MELSEC_CELL_CH1_INSP_CODE_LENGTH				5	

#define MELSEC_CELL_CH2_INNER_ID_LENGTH					20
#define MELSEC_CELL_CH2_MODEL_LENGTH					20
#define MELSEC_CELL_CH2_JIG_NAME_LENGTH					1
#define MELSEC_CELL_CH2_CH_NAME_LENGTH					1
#define MELSEC_CELL_CH2_ALIGN_RESULT_LENGTH				1
#define MELSEC_CELL_CH2_CONTACT_RESULT_LENGTH			1		
#define MELSEC_CELL_CH2_VERSION_LENGTH					20
#define MELSEC_CELL_CH2_TMD_NAME_LENGTH					20
#define MELSEC_CELL_CH2_INSP_TACT_TIME_LENGTH			5
#define MELSEC_CELL_CH2_INSP_RESULT_LENGTH				1	
#define MELSEC_CELL_CH2_INSP_CODE_LENGTH				5	

//2018-03-15,MGYUN, 추가
#define MELSEC_TURNTABLE_POS_LENGTH					1		
#define MELSEC_AJIG_SKIP_STATUS_LENGTH				1
#define MELSEC_BJIG_SKIP_STATUS_LENGTH				1
#define MELSEC_CJIG_SKIP_STATUS_LENGTH				1
#define MELSEC_DJIG_SKIP_STATUS_LENGTH				1
#define MELSEC_INTERLOCK_NAME_LENGTH				20
#define MELSEC_INTERLOCK_STATUS_LENGTH				1


//2018-03-13,MGYUN,추가 알람
#define MELSEC_ALARM_CODE_LENGTH					100
#define MELSEC_ALARM_CAUSE_CODE_LENGTH				100
#define MELSEC_FDC_ALARM_STATUS_LENGTH				1
#define MELSEC_FDC_ALARM_CASUE_LENGTH				1
/*
#define OPTICAL_LOADCONVYOR							0X550
#define OPTICAL_LDROBOT								0X551

#define OPTICAL_UPPER_SHUTTLE_CH1					0X552
#define OPTICAL_UPPER_SHUTTLE_CH2					0X553

#define OPTICAL_LOWER_SHUTTLE_CH1					0X554
#define OPTICAL_LOWER_SHUTTLE_CH2					0X555

#define OPTICAL_PA_TR_CH1							0X556
#define OPTICAL_PA_TR_CH2							0X557

#define OPTICAL_PA_STAGE_CH1						0X558
#define OPTICAL_PA_STAGE_CH2						0X559

#define OPTICAL_LD_TR_CH1							0X55A
#define OPTICAL_LD_TR_CH2							0X55B


//CELL ID WORD 영역에 추가
#define OPTICAL_JIG_A_CH1_CELLID                    0X600
#define OPTICAL_JIG_A_CH2_CELLID                    0X608
#define OPTICAL_JIG_B_CH1_CELLID                    0X610
#define OPTICAL_JIG_B_CH2_CELLID                    0X618
#define OPTICAL_JIG_C_CH1_CELLID                    0X620
#define OPTICAL_JIG_C_CH2_CELLID                    0X628
#define OPTICAL_JIG_D_CH1_CELLID                    0X630
#define OPTICAL_JIG_D_CH2_CELLID                    0X638
#define OPTICAL_ULDTR_CH1_CELLID                    0X640
#define OPTICAL_ULDTR_CH2_CELLID                    0X648
#define OPTICAL_ULD_ROBOT_CELLID                    0X650
*/




class CMonitorBank
{
public:
	CMonitorBank(void);
	~CMonitorBank(void);

	void WriteSwVersion(CString strVersion);
	void WriteEQPID(CString strEQPID);
	void WritePPID(CString strPPID);
	void WriteCimStatus(int nStatus);
	void WriteEqStatus(int nEqStatus);

	void SetInitData();

	void WriteMCRStatus(int nMCRName, BOOL nMCRStatus);							//MCR 통신 상태
	void WriteLDRobotPOS(double fX, double fY, double fZ, double fT);			//LD ROBOT TEACHING 쓰기
	void WriteULDRobotCH1POS(double fX, double fY, double fZ, double fT);		//ULD ROBOT CH1 TEACHING 쓰기
	void WriteULDRobotCH2POS(double fX, double fY, double fZ, double fT);		//ULD ROBOT CH1 TEACHING 쓰기
	void WriteEdgeAlign(CString nResult, CString strX, CString strY, CString strT);	//EdgeAlign Write
	void WritePREAlignCH1(int nResult, double fX, double fY, double fT);
	void WritePREAlignCH2(int nResult, double fX, double fY, double fT);
	void WriteMCRCellID(int nCh, CString strCellID);						//MCR CELL ID 기록
	void WriteDCRID(CString strCellID);										//DCR ID 기록	
	
	//2018-03-09,MGYUN, 추가  
	//void WritePortStatus(CString strPortStatus, CString strAvailable, 
	//					CString strAccess, CString strTransfer, CString strProcess);
	void WritePortStatus(int nPortNo, int nTransfer, int nProcessing);
		
	void WriteFDCLoader();                                                //FDC Loader Value 
	void WriteFDCZone();												  //FDC Zone Value 
	void WriteFDCUld();													  //FDC ULD Value 
	void WriteFDCUld_Stage();											  //FDC ULD Stage
	void WriteFDCGoodTray();											  //FDC for Good Tray
	void WriteFDCNGTray();												  //FDC for NG Tray
	void WriteFDCUtil();												  //FDC for UTIL
	void WriteFDCSem();													  //FDC for Sem
	void WriteStepID();													  // Step ID for Status of Cell in Loader position 
	//2018-03-12,MGYUN,추가
	void WriteTactTime(MAIN_TACK main_tact, CString strTactTime);		  //TACT TIME 기록
	//void WriteContactInfo(double dContactRate);							  //실시간 Contact 기록
	void WriteProductInfo(int nProductCount);							  //실시간 생산량 기록
	
	void WriteInDelay(int nDelay);									      //상류설비 IN DELAY
	void WriteAGVInDelay(int nDelay);									  //AGV IN DELAY 실시간(초) 추가
	void WriteAGVOutDelay(int nDelay);								      //OUT DELAY 실시간(초) 추가

	void WriteCellItemCH1(CELL_POS Pos);								  // CELL LOG 관련 항목 기록
	void WriteCellItemCH2(CELL_POS Pos);								  // CELL LOG 관련 항목 기록

	//2018-03-14,MGYUN,알람 기록 관련 함수
	void WriteAlarm(int nAlarmCnt, int nAlarmCode);							//알람명(정수형) 기록 함수
	void WriteAlarmClear(int nAlarmCnt);									//알람명 클리어 함수(0으로)
	void WriteFDCAlarmStatus(int nAlarmStatus);								//고객사 요청 알람 발생(1), 미발생(0) 
	void WriteAlarmCause(int nAlarmCnt, CString strAlarmCause);				//알람에 대한 원인명(텍스트) 
	void WriteAlarmCauseClear(int nAlarmCnt);								//알람원인 클리어 
	//2018-03-15,MGYUN, 추가
	void WriteTurnTablePos();												//턴테이블 위치(룰렛정보)
	void WriteJigSkipStatus();												//JIG SKIP 상태 관리
	void WriteInterLock(int nInterLockCnt, CString strInterlockName);		//설비 인터락 명칭 기록
	void WriteInterLockStatus(int nInterLockStatus);						//설비 인터락 상태 0 : 미발생 1 : 발생

	//2018-03-15,NAM,추가
	void WritePreContact(CString strContact);								// 현재 시각 기준 1시간 전 컨택률
	void WriteDayContact(CString strContact);								// 현재 시각 컨택률
	void WriteWeekContact(CString strContact);								// 시작 : 월요일 ~ 오늘 날짜까지의 컨택률
	void WriteMonthContact(CString strContact);								// 한달 컨택률 

	//2018-03-16, NAM, WRITE PRODUCTION QUANTITY TO DEVICE MONITORING
	void WritePreProduct(int nProductQuant);
	void WriteDayProduct(int nProductQuant);
	void WriteWeekProduct(int nProductQuant);
	void WriteMonthProduct(int nProductQuant);

};

